name: py35
channels:
- bioconda
- conda-forge
- defaults
- r
dependencies:
- bleach=1.4.2=py35_0
- python-dateutil=2.3=py35_0
- vcftools=0.1.15=1
- appnope=0.1.0=py35_0
- asn1crypto=0.22.0=py35_0
- backports=1.0=py35_1
- backports.functools_lru_cache=1.4=py35_1
- blas=1.1=openblas
- blinker=1.4=py_0
- boto3=1.5.22=py_0
- botocore=1.8.36=py_0
- cffi=1.11.2=py35_0
- chardet=3.0.4=py35_0
- clangdev=5.0.0=default_0
- cryptography=2.1.4=py35_0
- cycler=0.10.0=py35_0
- cymem=1.31.2=py35_0
- cytoolz=0.8.2=py35_0
- dask-core=0.16.1=py_0
- decorator=4.1.2=py35_0
- dill=0.2.7.1=py35_0
- docutils=0.14=py35_0
- entrypoints=0.2.3=py35_1
- freetype=2.8.1=0
- ftfy=4.4.2=py35_0
- graphviz=2.38.0=7
- h5py=2.7.1=py35_2
- hdf5=1.10.1=1
- html5lib=1.0.1=py_0
- icu=58.2=0
- idna=2.6=py35_1
- imageio=2.2.0=py35_0
- ipykernel=4.7.0=py35_0
- ipython=6.2.1=py35_1
- ipython_genutils=0.2.0=py35_0
- ipywidgets=7.1.1=py35_0
- jedi=0.11.1=py35_0
- jinja2=2.10=py35_0
- jmespath=0.9.3=py35_0
- jpeg=9b=2
- jsonschema=2.6.0=py35_0
- jupyter=1.0.0=py35_0
- jupyter_client=5.2.2=py35_0
- jupyter_console=5.2.0=py35_0
- jupyter_core=4.4.0=py_0
- libgpuarray=0.7.5=0
- libiconv=1.15=0
- libpng=1.6.34=0
- libsodium=1.0.15=1
- libtiff=4.0.9=0
- libxml2=2.9.7=0
- llvmdev=5.0.0=default_0
- mako=1.0.7=py35_0
- markupsafe=1.0=py35_0
- matplotlib=2.1.2=py35_0
- mistune=0.8.3=py_0
- msgpack-numpy=0.4.1=py_0
- msgpack-python=0.4.8=py35_0
- nbconvert=5.3.1=py_1
- nbformat=4.4.0=py35_0
- networkx=2.0=py35_1
- nltk=3.2.5=py_0
- notebook=5.4.0=py35_0
- numpy=1.14.0=py35_blas_openblas_200
- oauthlib=2.0.6=py_0
- olefile=0.44=py35_0
- openblas=0.2.20=7
- openmp=5.0.0=0
- pandas=0.22.0=py35_0
- pandoc=2.1.1=0
- pandocfilters=1.4.1=py35_0
- parso=0.1.1=py_0
- patsy=0.5.0=py35_0
- pexpect=4.3.1=py35_0
- pickleshare=0.7.4=py35_0
- pillow=5.0.0=py35_0
- plac=0.9.6=py35_0
- preshed=1.0.0=py35_0
- prompt_toolkit=1.0.15=py35_0
- ptyprocess=0.5.2=py35_0
- pycparser=2.18=py35_0
- pydot=1.2.3=py_0
- pygments=2.2.0=py35_0
- pygpu=0.7.5=py35_0
- pyjwt=1.5.3=py_0
- pyopenssl=17.4.0=py35_0
- pyparsing=2.2.0=py35_0
- pyperclip=1.6.0=py_0
- pyqt=5.6.0=py35_4
- pysocks=1.6.8=py35_1
- python-crfsuite=0.9.2=py35_0
- pytz=2017.3=py_2
- pywavelets=0.5.2=py35_1
- pyyaml=3.12=py35_1
- pyzmq=16.0.2=py35_3
- qt=5.6.2=h9e3eb04_4
- qtconsole=4.3.1=py35_0
- regex=2017.11.09=py35_0
- requests=2.18.4=py35_1
- requests-oauthlib=0.8.0=py35_1
- s3transfer=0.1.12=py35_0
- scikit-image=0.13.1=py35_0
- scikit-learn=0.19.1=py35_blas_openblas_201
- scipy=1.0.0=py35_blas_openblas_201
- seaborn=0.8.1=py35_0
- send2trash=1.4.2=py_0
- simplegeneric=0.8.1=py35_0
- sip=4.18=py35_1
- six=1.11.0=py35_1
- smart_open=1.5.6=py35_0
- spacy=2.0.7=py35_2
- statsmodels=0.8.0=py35_0
- termcolor=1.1.0=py35_1
- terminado=0.8.1=py35_0
- testpath=0.3.1=py35_0
- theano=1.0.1=py35_1
- thinc=6.10.2=py35_0
- toolz=0.8.2=py_2
- tornado=4.5.3=py35_0
- tqdm=4.19.5=py_0
- traitlets=4.3.2=py35_0
- twython=3.6.0=py35_0
- ujson=1.35=py35_0
- urllib3=1.22=py35_0
- wcwidth=0.1.7=py35_0
- webencodings=0.5=py35_0
- widgetsnbextension=3.1.3=py35_0
- wrapt=1.10.11=py35_0
- xgboost=0.7.post3=py35_1
- yaml=0.1.7=0
- zeromq=4.2.1=1
- bokeh=0.12.2=py35_0
- boto=2.48.0=py35h10f7326_1
- bz2file=0.98=py35_0
- ca-certificates=2017.08.26=ha1e5d58_0
- certifi=2018.1.18=py35_0
- gensim=3.1.0=py35h2e70219_0
- intel-openmp=2018.0.0=h8158457_8
- libcxx=4.0.1=h579ed51_0
- libcxxabi=4.0.1=hebd6815_0
- libedit=3.1=hb4e282d_0
- libffi=3.2.1=h475c297_4
- libgfortran=3.0.1=h93005f0_2
- mkl=2018.0.1=hfbd8650_4
- murmurhash=0.28.0=py35_0
- ncurses=6.0=hd04f020_2
- openssl=1.0.2n=hdbc3d79_0
- pip=9.0.1=py35h33ce766_4
- python=3.5.4=he720263_23
- readline=7.0=hc1231fa_4
- setuptools=38.4.0=py35_0
- sqlite=3.22.0=h3efe00b_0
- tk=8.6.7=h35a86e2_3
- wheel=0.30.0=py35h5c0b906_1
- xz=5.2.3=h0278029_2
- zlib=1.2.11=hf3cbc9b_2
- pip:
  - absl-py==0.1.10
  - backports.functools-lru-cache==1.4
  - dask==0.16.1
  - drivendata-submission-validator==1.0.0
  - en-core-web-sm==2.0.0
  - future==0.16.0
  - futures==3.1.1
  - hpsklearn (/Users/brendamainye/hyperopt-sklearn)==0.0.3
  - hyperas==0.4
  - hyperopt==0.1
  - ipython-genutils==0.2.0
  - jupyter-client==5.2.2
  - jupyter-console==5.2.0
  - jupyter-core==4.4.0
  - keras==2.1.3
  - markdown==2.6.11
  - nose==1.3.7
  - prompt-toolkit==1.0.15
  - protobuf==3.5.1
  - pymongo==3.6.0
  - smart-open==1.5.6
  - tensorflow==1.5.0
  - tensorflow-tensorboard==1.5.0
  - werkzeug==0.14.1
prefix: /Users/brendamainye/anaconda/envs/py35
